version: '3'
services:

    cord-holmes-server:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        command: bash -c "python /app/app.py & bash monitor_memory.sh"

