version: '3'
services:

    cord-holmes-server:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        env_file:
            - ./config/secrets
        command: bash -c "python /app/app.py & bash /app/monitor_memory.sh"

